version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: moirae-rabbitmq
    networks:
      - moirae
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASS}
    ports:
      - ${RABBIT_MQ_PORT}:5672
      - 15672:15672

  redis:
    image: redis:6.2-alpine
    container_name: moirae-redis
    networks:
      - moirae
    ports:
      - 6379:6379

  redis-commander:
    container_name: moirae-redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOST: redis
      # REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - '8081:8081'
    networks:
      - moirae
networks:
  moirae:
