version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: moirae-rabbitmq
    networks:
      - moirae
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASS}
    ports:
      - ${RABBIT_MQ_PORT}:5672
      - 15672:15672
networks:
  moirae:
