version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: moirae-rabbitmq
    networks:
      - moirae
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASS}
    ports:
      - ${RABBIT_MQ_PORT}:5672
      - 15672:15672

  redis:
    image: redis:6.2-alpine
    container_name: moirae-redis
    networks:
      - moirae
    ports:
      - 6379:6379

  redis-commander:
    container_name: moirae-redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOST: redis
      # REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - '8081:8081'
    networks:
      - moirae

  eventstoredb:
    image: eventstore/eventstore:21.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    networks:
    - moirae
networks:
  moirae:
